### ISSUE TITLE
Binance API Invalid

### ISSUE THREAD

**Issue by zakirattari26** [MohammedRashad/Crypto-Copy-Trader#24]
binance.exceptions.BinanceAPIException: APIError(code=-2014): API-key format invalid.
![image](https://user-images.githubusercontent.com/32705519/88465595-fc0e9900-cee1-11ea-82e4-a788b9e2bc9d.png)
![image](https://user-images.githubusercontent.com/32705519/88465607-1b0d2b00-cee2-11ea-8135-8e1cf7895be9.png)

**Comment by MohammedRashad** [comment]
can you share how do you input the keys? (not the actual key for sure)

**Comment by zakirattari26** [comment]
I tried several ways
1. Input from terminal 
2. Input directly to the db using sqlite browser
When I click to run it shows my balances both in master & slave in CLI that means it APIs were OK but all of a sudden it shows API key format invalid. Is there any specific way to input the API......?

**Comment by zakirattari26** [comment]
Below are SS 
![ct1](https://user-images.githubusercontent.com/32705519/88470383-655dce80-cf19-11ea-8f67-8ba3d54ed342.png)
![ct2](https://user-images.githubusercontent.com/32705519/88470386-6db60980-cf19-11ea-8ff9-55c3ed8e8348.png)
![ct3](https://user-images.githubusercontent.com/32705519/88470388-74dd1780-cf19-11ea-817c-e23b43794097.png)
![cc4](https://user-images.githubusercontent.com/32705519/88470391-7b6b8f00-cf19-11ea-9c9f-d5f42e05c21c.png)
This is Masters SS that successfully shows the Master accounts balances in CLI....
![ct5](https://user-images.githubusercontent.com/32705519/88470408-a1912f00-cf19-11ea-8528-15bc0590da4e.png)
This is Slaves SS that successfully shows the Slave accounts balances in CLI....
![ct6](https://user-images.githubusercontent.com/32705519/88470415-b372d200-cf19-11ea-99bd-57737a3b69ce.png)

**Comment by zakirattari26** [comment]
Traceback (most recent call last)
File "C:\Python37\lib\site-packages\flask\app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Python37\lib\site-packages\flask\app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "C:\Python37\lib\site-packages\flask\app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
raise value
File "C:\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "C:\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
raise value
File "C:\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "D:\Crypto-Copy-Trader-master\api.py", line 64, in run_process
manual_run()
File "D:\Crypto-Copy-Trader-master\api.py", line 47, in manual_run
client, slaves, old_orders = server_begin()
File "D:\Crypto-Copy-Trader-master\main.py", line 128, in server_begin
slave_binance = BinanceExchage(apiKey=i[0], apiSecret=i[1], pairs=symbols)
File "D:\Crypto-Copy-Trader-master\ExchangeInterfaces\BinanceExchange.py", line 13, in __init__
self.update_balance()
File "D:\Crypto-Copy-Trader-master\ExchangeInterfaces\BinanceExchange.py", line 19, in update_balance
account_information = self.connection.get_account()
File "C:\Python37\lib\site-packages\binance\client.py", line 1578, in get_account
return self._get('account', True, data=params)
File "C:\Python37\lib\site-packages\binance\client.py", line 222, in _get
return self._request_api('get', path, signed, version, **kwargs)
File "C:\Python37\lib\site-packages\binance\client.py", line 191, in _request_api
return self._request(method, uri, signed, **kwargs)
File "C:\Python37\lib\site-packages\binance\client.py", line 186, in _request
return self._handle_response()
File "C:\Python37\lib\site-packages\binance\client.py", line 215, in _handle_response
raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-2014): API-key format invalid.
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Que :- Is debugger causing the error ? Can I close the debugger ?

**Comment by mokolotron** [comment]
I see my lists of API keys in the database :( . One day I accidentally made a commit of my data base file. Try deleting the master and slave keys first using the delete button in the GUI. 
Then input yours api keys. 
Remember the must be 2 or more slaves in master branch (Issue #8).

**Comment by zakirattari26** [comment]
Thanks Bro...
Its working but only in two salves not more than 2
