### ISSUE TITLE
Trades not duplicated

### ISSUE THREAD

**Issue by Benoitseefor** [MohammedRashad/Crypto-Copy-Trader#49]
Hey!
Thank you so much for this amazing code, I'm currently trying to apply it in a raspberry pi (totally new in coding).

Would be nice if someone could help me: Code was working properly this morning, but right now it doesn't work anymore (trades not duplicated). Here the "error message" appearing in my cmd log.

Thanks!

DEBUG - Event came: {'e': 'executionReport', 'E': 1610824401562, 's': 'LINKUSDT', 'c': 'ios_56699c1a04254e2594d505a7d14a7d89', 'S': 'SELL', 'o': 'MARKET', 'f': 'GTC', 'q': '4.80000000', 'p': '0.00000000', 'P': '0.00000000', 'F': '0.00000000', 'g': -1, 'C': '', 'x': 'NEW', 'X': 'NEW', 'r': 'NONE', 'i': 1291098740, 'l': '0.00000000', 'z': '0.00000000', 'L': '0.00000000', 'n': '0', 'N': None, 'T': 1610824401562, 't': -1, 'I': 2647974736, 'w': True, 'm': False, 'M': False, 'O': 1610824401562, 'Z': '0.00000000', 'Y': '0.00000000', 'Q': '100.60670000'}                                                                                

2021-01-16 20:13:21,792 - DEBUG - Event came: {'e': 'executionReport', 'E': 1610824401562, 's': 'LINKUSDT', 'c': 'ios_56699c1a04254e2594d505a7d14a7d89', 'S': 'SELL', 'o': 'MARKET', 'f': 'GTC', 'q': '4.80000000', 'p': '0.00000000', 'P': '0.00000000', 'F': '0.00000000', 'g': -1, 'C': '', 'x': 'TRADE', 'X': 'FILLED', 'r': 'NONE', 'i': 1291098740, 'l': '4.80000000', 'z': '4.80000000', 'L': '20.92850000', 'n': '0.10045680', 'N': 'USDT', 'T': 1610824401562, 't': 68965818, 'I': 2647974737, 'w': False, 'm': False, 'M': True, 'O': 1610824401562, 'Z': '100.45680000', 'Y': '100.45680000', 'Q': '100.60670000'}"GET / HTTP/1.1" 200 -                                                                                 

2021-01-16 20:13:21,794 - DEBUG - Event came: {'e': 'outboundAccountPosition', 'E': 1610824401562, 'u': 1610824401562, 'B': [{'a': 'BNB', 'f': '0.00006165', 'l': '0.00000000'}, {'a': 'USDT', 'f': '688.42587600', 'l': '0.00000000'}, {'a': 'LINK', 'f': '0.00604000', 'l': '0.00000000'}]}

**Comment by Benoitseefor** [comment]
Exception in thread Thread-9:                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                               
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner                                                                                                          
    self.run()                                                                                                                                                                   
  File "/usr/lib/python3.7/threading.py", line 1166, in run                                                                                                                      
    self.function(*self.args, **self.kwargs)                                                                                                                                     
  File "/home/pi/.local/lib/python3.7/site-packages/binance/websockets.py", line 544, in _keepalive_account_socket                                                               
    callback = self._user_callback                                                                                                                                               
AttributeError: 'BinanceSocketManager' object has no attribute '_user_callback'                                                                                                  
                                                                                                                                                                                 
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 1166, in run
    self.function(*self.args, **self.kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/binance/websockets.py", line 544, in _keepalive_account_socket
    callback = self._user_callback
AttributeError: 'BinanceSocketManager' object has no attribute '_user_callback'

**Comment by mokolotron** [comment]
Hi. I also encountered this error sometimes, but I still haven't figured out what the problem is. The only thing I found was a [recommendation](https://github.com/sammchardy/python-binance/issues/449#issuecomment-578506762) from a user that helped to downgrade the python-binance library version to 0.7.3. Therefore, you can write a command ` pip install python-binance==0.7.3 `to do downgrade and see if there will be more errors.
