### ISSUE TITLE
I cannot start project

### ISSUE THREAD

**Issue by MaximMyDev** [MohammedRashad/Crypto-Copy-Trader#53]
Dear friend, I'm sorry I'm not an experienced python programmer. I cannot start project.
I did everything as in the instructions:
======= RESTART: D:\Install\OpenServer\domains\Crypto-Copy-Trader\api.py =======
Traceback (most recent call last):
  File "D:\Install\OpenServer\domains\Crypto-Copy-Trader\api.py", line 5, in <module>
    from Helpers.Helpers import server_begin
  File "D:\Install\OpenServer\domains\Crypto-Copy-Trader\Helpers\Helpers.py", line 2, in <module>
    from SlaveContainer import SlaveContainer
  File "D:\Install\OpenServer\domains\Crypto-Copy-Trader\SlaveContainer.py", line 2, in <module>
    from ExchangeInterfaces.BinanceExchange import BinanceExchange
  File "D:\Install\OpenServer\domains\Crypto-Copy-Trader\ExchangeInterfaces\BinanceExchange.py", line 4, in <module>
    from binance.exceptions import BinanceAPIException
ModuleNotFoundError: No module named 'binance'
>>>

**Comment by mokolotron** [comment]
This message mean that the dependence python-binance is not installed. 
Run `pip install python-binance==0.7.4` and copy log of result execution this command here.
If you didn't got any errors try to run Crypto-Copy-Trader again.

**Comment by MaximMyDev** [comment]
Dear friend, I was able to launch your project. You have done a great job, thank you for that!
After launching this error appears:
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Crypto-Copy-Trader\api.py", line 19, in socket_function
    container.first_copy(container.master.get_open_orders())
  File "D:\Crypto-Copy-Trader\ExchangeInterfaces\BinanceExchange.py", line 84, in get_open_orders
    quantityPart = self.get_part(o['symbol'], o["origQty"], o['price'], o['side'])
  File "D:\Crypto-Copy-Trader\ExchangeInterfaces\BinanceExchange.py", line 217, in get_part
    balance = float(get_context_balance(symbol)['free'])
  File "D:\Crypto-Copy-Trader\ExchangeInterfaces\BinanceExchange.py", line 204, in _get_base_balance
    return self.balance[self.symbols_info[symbol]['baseAsset']]
KeyError: 'TRXBTC'
Tell me what am I doing wrong?

**Comment by CuongITL** [comment]
> Dear friend, I was able to launch your project. You have done a great job, thank you for that!
> After launching this error appears:
> Exception in thread Thread-4:
> Traceback (most recent call last):
> File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 926, in _bootstrap_inner
> self.run()
> File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 870, in run
> self._target(*self._args, **self._kwargs)
> File "D:\Crypto-Copy-Trader\api.py", line 19, in socket_function
> container.first_copy(container.master.get_open_orders())
> File "D:\Crypto-Copy-Trader\ExchangeInterfaces\BinanceExchange.py", line 84, in get_open_orders
> quantityPart = self.get_part(o['symbol'], o["origQty"], o['price'], o['side'])
> File "D:\Crypto-Copy-Trader\ExchangeInterfaces\BinanceExchange.py", line 217, in get_part
> balance = float(get_context_balance(symbol)['free'])
> File "D:\Crypto-Copy-Trader\ExchangeInterfaces\BinanceExchange.py", line 204, in _get_base_balance
> return self.balance[self.symbols_info[symbol]['baseAsset']]
> KeyError: 'TRXBTC'
> Tell me what am I doing wrong?

Did you add "TRXBTC" to the "symbols.csv" ?
