### ISSUE TITLE
create_order failed Bitmex

### ISSUE THREAD

**Issue by allhq** [MohammedRashad/Crypto-Copy-Trader#55]
Hi Bro!
Pls help me. I try day and day. Whats wrong?
Master Account Bitmex
Slave Account Bitmextestnet. 
Many thanks

2021-03-26 16:01:26,100 - INFO - The Crypto-Copy-Trader starts launch
2021-03-26 16:01:26,107 - INFO - Reading configuration file...
2021-03-26 16:01:26,113 - INFO - 1 Slave accounts detected
2021-03-26 16:01:26,120 - INFO - Connecting to the master: Master...
2021-03-26 16:01:34,121 - INFO - Connecting to the slaves. Its can take time...
2021-03-26 16:01:42,863 - INFO - Open masters websocket... 
2021-03-26 16:01:43,646 - DEBUG - Event came: {'table': 'order', 'action': 'partial', 'keys': ['orderID'], 'types': {'orderID': 'guid', 'clOrdID': 'string', 'clOrdLinkID': 'symbol', 'account': 'long', 'symbol': 'symbol', 'side': 'symbol', 'simpleOrderQty': 'float', 'orderQty': 'long', 'price': 'float', 'displayQty': 'long', 'stopPx': 'float', 'pegOffsetValue': 'float', 'pegPriceType': 'symbol', 'currency': 'symbol', 'settlCurrency': 'symbol', 'ordType': 'symbol', 'timeInForce': 'symbol', 'execInst': 'symbol', 'contingencyType': 'symbol', 'exDestination': 'symbol', 'ordStatus': 'symbol', 'triggered': 'symbol', 'workingIndicator': 'boolean', 'ordRejReason': 'symbol', 'simpleLeavesQty': 'float', 'leavesQty': 'long', 'simpleCumQty': 'float', 'cumQty': 'long', 'avgPx': 'float', 'multiLegReportingType': 'symbol', 'text': 'string', 'transactTime': 'timestamp', 'timestamp': 'timestamp'}, 'foreignKeys': {'symbol': 'instrument', 'side': 'side', 'ordStatus': 'ordStatus'}, 'attributes': {'orderID': 'grouped', 'account': 'grouped', 'ordStatus': 'grouped', 'workingIndicator': 'grouped'}, 'filter': {'account': 1625735, 'symbol': 'XBTUSD'}, 'data': [{'orderID': 'b80c8ed4-ca5c-465a-b937-f18b29735982', 'clOrdID': '3cms_req_deal_368320258_2', 'clOrdLinkID': '', 'account': 1625735, 'symbol': 'XBTUSD', 'side': 'Sell', 'simpleOrderQty': None, 'orderQty': 966057, 'price': 54062.5, 'displayQty': None, 'stopPx': None, 'pegOffsetValue': None, 'pegPriceType': '', 'currency': 'USD', 'settlCurrency': 'XBt', 'ordType': 'Limit', 'timeInForce': 'GoodTillCancel', 'execInst': 'ReduceOnly', 'contingencyType': '', 'exDestination': 'XBME', 'ordStatus': 'New', 'triggered': '', 'workingIndicator': True, 'ordRejReason': '', 'simpleLeavesQty': None, 'leavesQty': 966057, 'simpleCumQty': None, 'cumQty': 0, 'avgPx': None, 'multiLegReportingType': 'SingleSecurity', 'text': 'Sent by 3commas', 'transactTime': '2021-03-26T13:56:29.250Z', 'timestamp': '2021-03-26T13:56:29.250Z'}]}
2021-03-26 16:01:46,353 - INFO - Launch complete. Now I can copy orders!
2021-03-26 16:01:46,373 - ERROR - Slave1: Error create order
Traceback (most recent call last):
  File "/home/mezo/Crypto-Copy-Trader/ExchangeInterfaces/BitmexExchange.py", line 205, in create_order
    quantity = self.calc_quantity_from_part(order.symbol, order.quantityPart,
  File "/home/mezo/Crypto-Copy-Trader/ExchangeInterfaces/BitmexExchange.py", line 95, in calc_quantity_from_part
    amount_usd = float(quantityPart) * float(self.get_balance())
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by metalblock** [comment]
Font work for me too

Il ven 26 mar 2021, 16:06 allhq ***@***.***> ha scritto:

**Comment by allhq** [comment]
?
