### ISSUE TITLE
Error while running project

### ISSUE THREAD

**Issue by GCarmona13** [MohammedRashad/Crypto-Copy-Trader#64]
Hi Mohammed, nice to meet you.

I was able to launch your project. You have done an awesome job, thank you so much!
Still I'm finding troubles, cause after launching this error appears:

2021-09-08 09:10:45,726 - INFO - The Crypto-Copy-Trader starts launch
2021-09-08 09:10:45,728 - INFO - Reading configuration file...
2021-09-08 09:10:45,729 - INFO - 2 Slave accounts detected
192.168.1.78 - - [08/Sep/2021 09:10:45] "GET /run HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Crypto-Copy-Trader-master\venv\Lib\site-packages\flask\app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Crypto-Copy-Trader-master\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Crypto-Copy-Trader-master\venv\Lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Crypto-Copy-Trader-master\venv\Lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Crypto-Copy-Trader-master\venv\Lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Crypto-Copy-Trader-master\venv\Lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Crypto-Copy-Trader-master\api.py", line 54, in run_process
    manual_run()
  File "C:\Crypto-Copy-Trader-master\api.py", line 27, in manual_run
    container = server_begin()
  File "C:\Crypto-Copy-Trader-master\Helpers\Helpers.py", line 65, in server_begin
    slave_container = SlaveContainer(config, symbols)
  File "C:\Crypto-Copy-Trader-master\SlaveContainer.py", line 20, in __init__
    self.logger.info(f"Connecting to the master: {config['master']['name']}...")
TypeError: list indices must be integers or slices, not str
192.168.1.78 - - [08/Sep/2021 09:10:46] "GET /run?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
192.168.1.78 - - [08/Sep/2021 09:10:46] "GET /run?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
192.168.1.78 - - [08/Sep/2021 09:10:46] "GET /run?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
192.168.1.78 - - [08/Sep/2021 09:10:47] "GET /run?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -

I'm sorry, but I'm not an experienced python programmer at all, could you please help me to find what I'm doing wrong?
Thank you in advance!
BR

**Comment by mokolotron** [comment]
Hi, maybe mistake in `config.json`. Can you show your config file without api keys
